site_name: Biblioteca Digital Ucuenca

nav:
    - Inicio: index.md
    - Guía de Digitalización: digitalizacion.md
    - Directrices de Metadatos:
        - metadatos/directrices.md
        - Campos: 
          - Descripción General: metadatos/campos.md
          - 1. Título: metadatos/titulo.md
          - 2. Título Alternativo: metadatos/tit_alter.md
          - 3. Autor: metadatos/autor.md
          - 4. Materia: metadatos/materia.md
          - 5. Palabras clave: metadatos/pclave.md
          - 6. Resumen: metadatos/resumen.md
          - 7. Abstract: metadatos/abstract.md
          - 8. Fuente: metadatos/fuente.md
          - 9. Tipo de Publicación: metadatos/tipo_pub.md
          - 10. Publicaciones relacionadas: metadatos/pub_rel.md
          - 11. Serie o Colección: metadatos/serie.md
          - 12. Edición: metadatos/edicion.md
          - 13. Cobertura temporal: metadatos/cob_temp.md
          - 14. Cobertura geográfica: metadatos/cob_geo.md
          - 15. Colaborador: metadatos/colaborador.md
          - 16. Identificador: metadatos/identif.md
          - 17. Identificador alternativo: metadatos/identif_alter.md
          - 18. Editorial: metadatos/editorial.md
          - 19. Nivel de Acceso: metadatos/acceso.md
          - 20. Condición de la licencia: metadatos/licencia.md
    - About: about.md

markdown_extensions:
    - admonition
    - footnotes
    - attr_list
    - codehilite:
        guess_lang: false
    - def_list
    - md_in_html
    - meta
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

theme: 
  name: material 
  features:
    - navigation.tracking
    - navigation.expand
    - navigation.tabs 
    - navigation.indexes
    - navigation.top

footer: "Creado por el Centro de Documentación Regional Juan Bautista Vázquez"
