site_name: Biblioteca Digital Ucuenca

nav:
    - Inicio: index.md
    - Guía de Digitalización: digitalizacion.md
    - Directrices de Metadatos:
        - metadatos/directrices.md
        - Libros: 
          - Descripción General: metadatos/libros.md
          - Título: metadatos/titulo.md
          - Título Alternativo: metadatos/tit_alter.md
          - Autor: metadatos/autor.md
        - Revistas: metadatos/revistas.md
        - Tesis: metadatos/tesis.md
    - About: about.md

markdown_extensions:
    - admonition
    - footnotes
    - attr_list
    - codehilite:
        guess_lang: false
    - def_list
    - md_in_html
    - meta
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

theme: 
  name: material 
  features:
    - navigation.expand
    - navigation.tabs 
    - navigation.indexes
    - navigation.top

footer: "Creado por el Centro de Documentación Regional Juan Bautista Vázquez"
